name: Create and push Docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/Checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: install dependencies
        run: npm install
      - name: set up Docker build
        uses: docker/setup-buildx-action@v2
      - name: Login into Github Docker packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/high-score-tables:${{ github.sha }} .
      - name: Tag Docker image
        run: |
          docker tag ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/high-score-tables:${{ github.sha }} ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/high-score-tables:latest
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/scores-table:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/scores-table:latest
